security:
    encoders:
        # Symfony\Component\Security\Core\User\User: plaintext
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_API:         ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username  
        # in_memory:
        #     memory:
        #         users:
        #             restapi:  { password: secretpw, roles: [ 'ROLE_API' ] }

    firewalls:
        oauth_token:                                   # Everyone can access the access token URL.
            pattern: ^/oauth/v2/token
            security: false
        doc:                                   # Everyone can access the access token URL.
            pattern: ^/api/doc
            security: false
        api:
            pattern: ^/                                # All URLs are protected
            fos_oauth: true                            # OAuth2 protected resource
            stateless: true                            # Do no set session cookies
            anonymous: false
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # main:
        #     pattern: ^/
        #     anonymous: ~
        #     stateless:  true
        #     http_basic:
        #         realm: "Demo REST API (username: restapi, password: secretpw)"
